//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos2
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        public int id__libro { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public string autor { get; set; }
        public string nombre { get; set; }
        public string fecha_publicacion { get; set; }
    }
}
